// This file is generated by Astro DB
declare module 'astro:db' {
	export const Guestbook: import("@astrojs/db/runtime").Table<
		"Guestbook",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Guestbook","primaryKey":true}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Guestbook","primaryKey":false,"optional":false}},"message":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"message","collection":"Guestbook","primaryKey":false,"optional":false}},"website":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"website","collection":"Guestbook","primaryKey":false,"optional":true}},"createdAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"createdAt","collection":"Guestbook"}}}
	>;
}
